### ISSUE TITLE
KeyError: 'fix_mod'

### ISSUE THREAD

**Issue by alessandro-vai** [SimpleNumber/aa_stat#12]
Dears,

I ran an open search using ionbot (https://ionbot.cloud/). I formatted the results as a csv file with all the columns required by AA_stat. However, I get the following error:
```
INFO: [08:50:57] Starting...
Traceback (most recent call last):
  File "/miniconda3/envs/aa_stat/bin/AA_stat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/miniconda3/envs/aa_stat/lib/python3.11/site-packages/AA_stat/main.py", line 47, in main
    AA_stat.AA_stat(params_dict, args)
  File "/miniconda3/envs/aa_stat/lib/python3.11/site-packages/AA_stat/AA_stat.py", line 322, in AA_stat
    logger.debug('Fixed modifications: %s', params_dict['fix_mod'])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'fix_mod'
```
The column in the csv file which contains the modifications list is formatted as the 'Assigned Modifications' column in the MSFragger ouput e.g:  '10K(56.0262), N-term(119.0371)', where in this case N-term(119.0371) is the fixed modification. I am not sure this is the correct way of specifying modifications for AA_stat to be able to parse them. Also I am not sure the error is linked to this.

Thank you for your help.

Alessandro

**Comment by levitsky** [comment]
Hi @alessandro-vai,

Thank you for your patience. Because we only use AA_stat with pepXML input, we lost track of CSV support for a while and added some features based on metadata available in pepXML files. Because of that, AA_stat stopped working with CSV input.

I made some changes in the last commit, which is still a work in progress. These changes require some extra input on the command line. At this time unfortunately AA_stat requires very specific input format for some fields. The format corresponds to data layout in pepXML.

**Note**: all these features are related to the localization functionality. If you are not using it, the below options will not have much effect.

To be exact, you need to specify these parameters on command line when using CSV input:
 - `--fmods` are *fixed* modifications as specified in your search parameters, in the format of a Python dict (or JSON object) with amino acids for keys and new masses for values, e.g.: `--fmods "{'C': 160.0307, 'K': 357.2579, 'H-': 230.1708}"`;
 - `--vmods` are *variable* modifications as specified in your search parameters, in the format of a Python list of pairs , e.g.: `--vmods "[('M', 15.9959), ('N-term', 42.0106)]"`;
 - `--enzyme` is the enzyme specificity. This is the least important but it helps in interpretations of certain artefact mass shifts. The format is like this (for trypsin): `--enzyme "{'cut': 'KR', 'no_cut': 'P', 'sense': 'C'}"`. (**Edit:** no need to specify it for trypsin.)

AA_stat will run without these parameters, but this will affect localization results. If you don't need localization, you can omit them.

For `--fmods` and `--vmods`, the keys can be amino acids, `"N-term", "C-term", "Protein N-term", "Protein C-term", and things like "N-term A".
I probably need to come up with a more convenient way to specify this on the command line but this what I was able to do relatively quickly.

Also, the assigned modifications column in the input currently must be in a different format as well, e.g.: `['230.171@0', '357.258@7']`.

**Comment by alessandro-vai** [comment]
Ok, I was able to get it working.
Thanks again

**Comment by levitsky** [comment]
Hi @alessandro-vai, I made another pass at AA_stat to make it more usable. The before options work, but you can also specify the mods in human-friendly format, like: `+57.0215 @ C, +229.1630 @ N-term` etc. Enzyme specificity can be provided like with X!Tandem: e.g. `[RK]|{P}` for trypsin. Also you can specify fixed and variable mods in the config file in the same format, under `[modifications]` section, using `configured fixed modifications` and `configured variable modifications` options, respectively.
Let me know if you run into other issues with CSV input. Cheers!
