### ISSUE TITLE
Files required for aa_stat MSFragger OpenSearch

### ISSUE THREAD

**Issue by BenSamy2020** [SimpleNumber/aa_stat#4]
Greetings,

I would like to confirm with you the required files for aa_stat to analysis MSFragger (FragPipe) OpenSearch results.
Briefly, I performed my searches using FragPipe GUI with default OpenSearch settings.

For the:
--params PARAMS
**Am I required to provide the fragger.params file?** If this is not the file, what is the file name that FragPipe provides as output that I can utilize? 

-v {0,1,2,3}, --verbosity {0,1,2,3}
**What does verbosity mean in the context of OpenSearch data analysis?
What is the difference between 0,1,2,3?**

--mgf MGF [MGF ...]
**If I provide the .mgf file, am I also required to provide the corresponding mzml file too?**

-db FASTA, --fasta FASTA
**Is this fasta file the one provided to FragPipe before searching the .mgf files?
My decoy are labelled as REV_, where do I find the AA_stat params file and where must I specify REV_?**

--os-params OS_PARAMS
**FragPipe did not provide any output specifically for FragPipe OpenSearch parameters. I utilised the default OpenSearch Parameter file. Can I provide the default file?**

It would be amazing if you could provide a step by step tutorial on how to utilize the output files from FragPipe OpenSearch to be analyzed by aa_stat (.PDF file with multiple screenshot to show where to obtain these files and with commands to be entered into cmd). This will be extremely useful for a non-programmer like to be make full use of this amazing tool. **_Also it would be great if you can speak to Alexy and integrate this tool directly into FragPipe GUI. It will be extremely convenient._**   
     
Lastly, I would like to thank you in advance for your assistance. Apologies, I am extremely new to this tool hence all of these above questions.

Regards,
Ben

**Comment by SimpleNumber** [comment]
Hi Ben!

> Am I required to provide the fragger.params file? If this is not the file, what is the file name that FragPipe provides as output that I can utilize?

No, these parameters for AA_stat.  You can skip this attribute then the default parameters will be used( located at AA_stat/default.cfg). If you wanna customize AA_stat parameters you can use the default.cfg as an example. Description of all parameters you can find in AA_stat's README file or at github main page of the project.

> What does verbosity mean in the context of OpenSearch data analysis?
> What is the difference between 0,1,2,3?

This attribute influences the amount of information you will see in a terminal. A higher number means more info.  It is mostly for debugging. 

> --mgf MGF [MGF ...]
> If I provide the .mgf file, am I also required to provide the corresponding mzml file too?

No, you can provide either .MGF files or .MZML. 

> -db FASTA, --fasta FASTA
> Is this fasta file the one provided to FragPipe before searching the .mgf files?
> My decoy are labelled as REV_, where do I find the AA_stat params file and where must I specify REV_?

This attribute is needed when AA_stat is used in "AA_search" mode. AA_search mode launches open searches using MSFragger. If you already have open search results, there is no need to use AA_search. 
The used prefix should be specified in the parameters file. As I wrote above you can use default.cfg as an example to create your custom parameters, or you can edit default.cfg file.

> --os-params OS_PARAMS
> FragPipe did not provide any output specifically for FragPipe OpenSearch parameters. I utilised the default OpenSearch Parameter file. Can I provide the default file?

This is also needed only in AA_search mode to perform open searches. You do not need to use this attribute, since you already have your search results.

Regards,
Julia

**Comment by BenSamy2020** [comment]
Greetings Julia,

Thank you for your rapid response. Will perform the analysis tomorrow and will contact you if I run into any issues. 

Regards,
Ben
